# -*- coding: utf-8 -*-
"""1.DataConvert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AaB1lzAj8jz6P8OmRcUU9gjuIphIWGOX

### 데이터 변환

##### xlsx to csv   
##### csv to csv   


- 구분자 쉼표
- 인코딩 방식 UTF-8
- 결측치 NaN
"""

import pandas as pd

"""CNTT데이터 CONVERT"""

data = pd.read_csv('CNTT.csv')
data.head()

data.to_csv('CNTTconvert.csv',sep=',',na_rep='',encoding='UTF-8',index=False)



"""FPINFO 데이터 CONVERT"""

data = pd.read_csv('FPINFO.csv')
data.head()

data.to_csv('FPINFOconvert.csv',sep=',',na_rep='',encoding='UTF-8',index=False)



"""cust.22400데이터 CONVERT"""

data = pd.read_excel('cust.22400.xlsx')
data.head()

data.to_csv('cust.22400convert.csv',sep=',',na_rep='',encoding='UTF-8',index=False)



"""CLAIM 데이터 CONVERT"""

data = pd.read_csv('CLAIM.csv')
data.head()

data.to_csv('CLAIMconvert.csv',sep=',',na_rep='',encoding='UTF-8',index=False)

