# -*- coding: utf-8 -*-
"""InsuranceData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iG-IL4ScwZR7dGz9U86Gshh7K2Ym1i_N
"""

!pip install numpy
!pip install pandas

#모듈IMPORT
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')

# CNTT_DATA, CUST_DATA, FPINFO_DATA 병합 파일 불러오기
cust_cntt_fpinfo = pd.read_csv('CNTT_FPINFO_CUST.csv', sep = ',', encoding = 'UTF-8')
cust_cntt_fpinfo

cust_cntt_fpinfo.info()

cust_cntt_fpinfo.drop(['Unnamed: 0'], axis=1, inplace = True)

cust_cntt_fpinfo.info()

# 정제된 CLAIM_DATA 파일 불러오기
claim = pd.read_csv('ProcessedCLAIMData.csv', sep = ',', encoding = 'UTF-8')
claim

claim.info()

claim.drop(['Unnamed: 0'], axis=1, inplace = True)

claim.info()

# 하나의 보험 데이터(InsuranceData)로 병합
insurance = pd.merge(cust_cntt_fpinfo, claim)
insurance

insurance.info()

insurance.isnull().sum()

insurance.to_csv('InsuranceData.csv')

