# -*- coding: utf-8 -*-
"""claim_corr2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lErAkWW9nxMTRmS7l9wc0LqOEvarU0n9
"""

!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install warnings

# Data
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

#warning
import warnings
warnings.filterwarnings('ignore')

# 에디터 이용시 아래 코드로 대체
#uploaded = pd.read_csv('human_activity/features.txt', sep='\s+', header=None, names=['column_index', 'column_name'])
features = pd.read_csv('merged_claim_data.csv', sep = ',', encoding = 'utf-8', error_bad_lines=False, engine = 'python', header = None)
features = features.rename(columns=features.iloc[0])
features = features.drop(features.index[0])#첫 row는 컬럼명이 들어간 더미데이터이므로 삭제
features = features.astype('float')

features

#학습 및 테스트용 데이터를 데이터 프레임으로 로딩
features = features[['SIU_CUST_YN','SEX','AGE','FP_CAREER','MAX_PRM','RESL_CD1','ACCI_OCCP_GRP','CHME_LICE_NO','DMND_AMT','PAYM_AMT','NON_PAY_RATIO','HEED_HOSP_YN','CLAIM_CNT','TOTAL_VLID_HOSP_OTDA','HOSP_VARIES','HOSP_DVSN_VARIES','CHME_LICE_COUNT']]

corr_data = features.corr()
corr_data = corr_data.apply(lambda x: round(x ,2))
corr_data

corr_data.to_csv('corr_data.csv')

s = corr_data.unstack()
s

# 변수간의 상관관계
df = pd.DataFrame(s[s < 1].sort_values(ascending=False), columns=['corr'])
df.style.background_gradient(cmap='viridis')





