# -*- coding: utf-8 -*-
"""cust_claim_multireg2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WCK-BZ-tU757UN7ENSnsu-3UFI5qoEpW
"""

!pip install numpy
!pip install pandas
!pip install sklearn
!pip install statsmodels
!pip install matplotlib
!pip install seaborn

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

import matplotlib.pyplot as plt
import seaborn as sns

#타 에디터 이용시 아래 코드로 대체
#uploaded = pd.read_csv('human_activity/features.txt', sep='\s+', header=None, names=['column_index', 'column_name'])
features = pd.read_csv('merged_claim_data.csv', sep = ',', encoding = 'utf-8', error_bad_lines=False, engine = 'python', header = None)
features = features.rename(columns=features.iloc[0])

features = features.drop(features.index[0])#첫 row는 컬럼명이 들어간 더미데이터이므로 삭제
features = features.astype('float')

#학습 및 테스트용 데이터를 데이터 프레임으로 로딩
x = features[['SIU_CUST_YN','SEX','AGE','FP_CAREER','MAX_PRM','RESL_CD1','ACCI_OCCP_GRP','CHME_LICE_NO','DMND_AMT','PAYM_AMT','NON_PAY_RATIO','HEED_HOSP_YN','CLAIM_CNT','TOTAL_VLID_HOSP_OTDA','HOSP_VARIES','HOSP_DVSN_VARIES','CHME_LICE_COUNT']]
y = features['SIU_CUST_YN']

x = sm.add_constant(x, has_constant = 'add')

#다중 회귀모델 작성
mm = sm.OLS(y, x)
fitted_mm = mm.fit()

#분석 요약본
fitted_mm.summary()



#p value는 귀무가설을 기각할 지에 대한 기준이 되는 수치이다. 
#그 값이 작을수록 그 정도가 약하다고 보며, 특정 값 (대개 0.05나 0.01 등) 보다 작을 경우 귀무가설을 기각한다.